name: CI

on:
  pull_request:
  push:
    branches:
      - 'dvim-tracker'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'

      - name: Install npm packages
        run: |
          set -e
          npm install --force

      - name: Build UI
        run: |
          set -e
          npm run build:production

      - name: Run eslint
        run: |
          set -e
          npm run lint

      - name: Deploy
        if: github.repository == 'tanjo3/tww-rando-tracker' && github.ref == 'refs/heads/dvim-tracker'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY }}
          force_orphan: true
          publish_branch: gh-pages-dvim
          publish_dir: ./dist
